### PR TITLE
Check if minBound is negative in decimal

### LINKED ISSUE #62: wrong formatting of Word types
`format (left 3 '0') (0::Word8)` gives wrong result `"0-0"`, instead of `"000"`.

Example:
```haskell
$ ghci
GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help
Prelude> :m +Formatting
Prelude Formatting> :m +Data.Word
Prelude Formatting Data.Word> format (left 3 '0') (0::Int)
"000"
Prelude Formatting Data.Word> format (left 3 '0') (0::Word8)
"0-0"
```

### PR DESCRIPTION
**Pull request by axman6-da**
Fixes #62

### CODE REVIEW

**Comment by AJChapman** [comment]
Thanks @axman6-da. Would you mind adding a regression test for this as well?

**Comment by axman6-da** [comment]
I've added a couple of tests, and cleaned up things a bit - I'm happy to revert and try and match the style if you prefer, this just felt more consistent with how I've used and see spec in the past.

File: test/Spec.hs [hunk 1]
```diff
@@ -15,55 +15,30 @@ main = hspec spec
...
+      it "format (later id <> later id) \"x\"" $ format (later id Data.Monoid.<> later id)    "x" `shouldBe` "xx"
+      it "format (later id <> later id) \"x\"" $ format (later id Data.Semigroup.<> later id) "x" `shouldBe` "xx"
+
+    describe "https://github.com/chrisdone/formatting/issues/31" $ do
+      it "10^6-1" $ F.format F.int (10 ^ (16 :: Int) - 1 :: Int) `shouldBe` "9999999999999999"
+
+    describe "https://github.com/chrisdone/formatting/issues/28" $ do
+      it "-100"         $ sformat (groupInt 3 ',') (-100 :: Int)       `shouldBe` "-100"
+      it "-100,000,000" $ sformat (groupInt 3 ',') (-100000000 :: Int) `shouldBe` "-100,000,000"
+      it "100,000,000"  $ sformat (groupInt 3 ',') (-100000000 :: Int) `shouldBe` "-100,000,000"
```
Comment (axman6-da) [inline test/Spec.hs:29]: This looks like it's wrong but is what was originally in the tests
